name: Build and Push Docker Image (with Cache)

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd app
          npm ci

      - name: Run tests
        run: |
          cd app
          npm test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push image with cache
        uses: docker/build-push-action@v5
        with:
          context: ./app   # 👈 point to app folder for Docker build
          file: ./app/Dockerfile
          push: true
          tags: arlajoshna/demo-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
