name: Build (with Docker layer cache)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Debug step: List contents of root and app directory to confirm Dockerfile presence
      - name: List root directory contents
        run: ls -la

      - name: List app directory contents
        run: ls -la ./app || echo "app directory not found"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub (optional)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image (with GitHub Actions cache)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./app/Dockerfile
          push: false
          tags: demo-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
