name: Log Analyzer
on:
  workflow_run:
    workflows: ["Build (with Docker layer cache)"]
    types: [completed]

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v4
      - name: Download logs or artifacts
        run: echo "Fetch logs here or use artifacts"
      - name: Run log analyzer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 scripts/log_analyzer.py --run-id ${{ github.event.workflow_run.id }}
